version: "3.9"
services:
  rabbit_server:
    container_name: RabbitMQ
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  diploma_chat:
    depends_on:
      rabbit_server:
        condition: service_healthy
    container_name: DiplomaChat
    restart: on-failure
    build:
      dockerfile: ./DiplomaChat/Dockerfile
      context: ./
    ports:
      - "8080:80"
    links:
      - "rabbit_server:rabbit"

  diploma_chat_sso:
    container_name: DiplomaChat_SingleSignOn
    restart: on-failure
    build:
      dockerfile: ./DiplomaChat.SingleSignOn/Dockerfile
      context: ./
    ports:
      - "18080:80"
      - "11443:443"
      - "44317:44317"
