version: "3.9"
services:
  rabbit_server:
    container_name: RabbbitMQ
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  diploma_chat:
    depends_on: 
      rabbit_server:
        condition: service_healthy
    container_name: DiplomaWork
    restart: on-failure
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "8080:80"
      - "49443:443"
    links:
      - "rabbit_server:rabbit"