version: "3.9"
services:
  rabbit_server:
    container_name: RabbitMQ
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
  sql_server:
    container_name: SqlServer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: "Y"

  diploma_chat:
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    depends_on:
      rabbit_server:
        condition: service_healthy
    container_name: DiplomaChat
    restart: on-failure
    build:
      dockerfile: ./DiplomaChat/Dockerfile
      context: ./
    ports:
      - "8080:80"
    links:
      - "rabbit_server:rabbit"

  diploma_chat_sso:
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "https://+:443;http://+:80"
    container_name: DiplomaChat_SingleSignOn
    restart: on-failure
    build:
      dockerfile: ./DiplomaChat.SingleSignOn/Dockerfile
      context: ./
    ports:
      - "18080:80"
      - "11443:443"
